version: '3'
services:
  node:
    image: node:16-alpine
    working_dir: /home/conteudo
    container_name: nodejs
    user: node
    stdin_open: true
    tty: true
    volumes:
      - .:/home/conteudo
    ports:
      - 3000:3000
