version: '3.9'

services:

  db:
    image: mysql:5.7
    container_name: mysql-curso
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-vol:/var/lib/mysql
    ports:
      - '3306:3306'
volumes:
  mysql-vol:
