version: '3'
services:
  db:
    image: mysql:5.7
    container_name: same-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-vol:/var/lib/mysql
      - .:/pc-host
    ports:
      - '3306:3306'

volumes:
  mysql-vol:
